name: CAS Automation
on: push
env:
  CAS_API_KEY: ${{ secrets.CAS_API_KEY }}

jobs:
  build:
    name: CAS Automation Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./

